#!/usr/bin/env bash
set -euo pipefail

log() {
  printf "[%s] %s\n" "$(date '+%H:%M:%S')" "$*"
}

have() { command -v "$1" &>/dev/null; }

if ! have zsh; then
  log "Installing zsh"
  if [[ "${OSTYPE:-}" == darwin* ]]; then
    brew install zsh
  else
    sudo apt update && sudo apt install -y zsh
  fi
fi

OHMYZSH_DIR="$HOME/personal/oh-my-zsh"
if [[ ! -d "$OHMYZSH_DIR" ]]; then
  log "Installing Oh My Zsh"
  ZSH="$OHMYZSH_DIR" RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [[ "$SHELL" != *zsh ]]; then
  log "Setting zsh as default shell"
  if [[ "${OSTYPE:-}" == darwin* ]]; then
    chsh -s "$(which zsh)"
  else
    sudo chsh -s "$(which zsh)" "$(whoami)"
  fi
fi

AUTOSUGGEST_DIR="$HOME/personal/zsh-autosuggestions"
if [[ ! -d "$AUTOSUGGEST_DIR" ]]; then
  log "Installing zsh-autosuggestions"
  git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions "$AUTOSUGGEST_DIR"
fi

POWERLEVEL10K_DIR="$OHMYZSH_DIR/custom/themes/powerlevel10k"
if [[ ! -d "$POWERLEVEL10K_DIR" ]]; then
  log "Installing Powerlevel10k"
  git clone --depth 1 https://github.com/romkatv/powerlevel10k.git "$POWERLEVEL10K_DIR"
fi

log "Done"
