#!/usr/bin/env bash

readonly NERD_FONTS_GIT="https://github.com/ryanoasis/nerd-fonts/releases/download"
readonly RELEASE_VERSION="v3.4.0"
readonly FONTS_DIR="${HOME}/.local/share/fonts"
readonly FONTS_RAW_DIR=/tmp/fonts


declare -a fonts=(
    "${NERD_FONTS_GIT}/${RELEASE_VERSION}/BitstreamVeraSansMono.zip"
    "${NERD_FONTS_GIT}/${RELEASE_VERSION}/FiraMono.zip"
)

valiade_fonts(){
    for font_url in "${fonts[@]}"; do
        local filename=$(basename "$font_url" .zip)
        if [[ -z $(find "$FONTS_DIR" -name "${font_name}*" -type f) ]]; then
            return 1
        fi
    done
    return 0
}

if validate_fonts; then
    echo "Fonts already installed."
    exit 0
fi

[[ ! -d "$FONTS_DIR" ]] && mkdir -p "$FONTS_DIR"


mkdir -p $FONTS_RAW_DIR
cd $FONTS_RAW_DIR

for font_url in "${fonts[@]}"; do
    wget "${font_url}"
    unzip "$(basename "$font_url")" -d $fonts_dir
done

if ! command -v fc-cache &> /dev/null; then
    echo "fc-cache not found. Trying to install."
    sudo apt update && sudo apt install -y fontconfig
fi

fc-cache -fv

rm -rf "$FONTS_RAW_DIR"

