#!/usr/bin/env bash


install_fzf(){
   fzf_dir="$HOME/personal/fzf"
   [ ! -d "$fzf_dir" ] && git clone --depth 1 https://github.com/junegunn/fzf.git "$fzf_dir"
   pushd "$fzf_dir"
   # Only install the binary, no prompts and autocompletion
   ./install --bin
   popd
}

install_fzf

if ! command -v tree &> /dev/null; then
   sudo apt update && sudo apt install tree
fi
