#!/usr/bin/env bash

tmux_plugins_dir=$HOME/personal/tmux/plugins
mkdir -p "$tmux_plugins_dir"


if ! command -v tmux &> /dev/null; then
    sudo apt update && sudo apt install -y tmux
fi

if [ ! -d "${tmux_plugins_dir}/tpm" ]; then
    git clone https://github.com/tmux-plugins/tpm "$tmux_plugins_dir/tpm"
fi

if [ ! -d "$tmux_plugins_dir/resurrect" ]; then
    git clone https://github.com/tmux-plugins/tmux-resurrect.git "$tmux_plugins_dir/resurrect"
fi

