#!/usr/bin/env bash
if ! command -v zsh &> /dev/null; then
    sudo apt update && sudo apt install -y zsh
fi

readonly LOCAL_OHMYZSH_DIR="$HOME/personal/oh-my-zsh"

mkdir -p "$(dirname $LOCAL_OHMYZSH_DIR)"
if  [[ ! -d "$LOCAL_OHMYZSH_DIR" && ! -f "$LOCAL_OHMYZSH_DIR/oh-my-zsh.sh" ]]; then
    sudo chsh -s $(which zsh)
    ZSH="$LOCAL_OHMYZSH_DIR" RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

readonly AUTOCOMPLETE="$HOME/personal/autocomplete"
if [[ ! -d "$AUTOCOMPLETE" ]]; then
    echo "Installing zsh-autocomplete..."
    git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git "$AUTOCOMPLETE"
fi

readonly POWERLEVEL10K_DIR="$LOCAL_OHMYZSH_DIR/custom/themes/powerlevel10k"
if [[ ! -d "$POWERLEVEL10K_DIR" ]]; then
    echo "Installing Powerlevel10k theme..."
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$POWERLEVEL10K_DIR"
fi

